apiVersion: v1
kind: Pod
metadata: 
  name: my-pod 
spec:
  containers:
    - name: my-con 
      image: nginx:1.0
      ports:
        - containerPort: 80
      env:
        - name: user_data
          valueFrom:
            configMapKeyRef:
              key: user_data
              name: divya
      volumeMounts:
        - name: my-vol 
          mountPath: /tmp/
  volumes:
    - name: my-vol
      configMap:
        name: divya
        items:
          - key: user_data
            path: usr.txt
